# Numpy


In [ ]:
# pip install numpy # For installation
# Syntax : pip install <package_name>  ==>used to install a package from the Python Package Index (PyPI) or other package repositories.
# pip: package manager for Python that allows users to install and manage software packages written in Python.

In [3]:
import numpy as np  #import numpy

# import            numpy             as   np   
# keyword     library/modules name        alias 

In [ ]:
# import numpy

In [ ]:
# numpy.array([1,2,3])

In [ ]:
# we cannot apply mathematical operators directly on lists. element-wise operations with lists require a bunch of code
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

In [7]:
# Create array
a=np.array([1,2,3,4])

In [8]:
print(a)

[1 2 3 4]


In [9]:
type(a)

numpy.ndarray

In [10]:
len(a)

4

In [11]:
L=list(range(1,11))

In [12]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
len(L)

10

In [14]:
type(L)

list

In [15]:
# Create array using list
a=np.array(L)

In [16]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# we cannot apply mathematical operators directly on lists. element-wise operations with lists require a bunch of code
# we can apply mathematical operators directly on Array

In [17]:
# List
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
L+L # This operation does not add . 2 list will be concat

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
L+2

TypeError: can only concatenate list (not "int") to list

In [26]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# element-wise operations with lists require a bunch of code

In [25]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [23]:
# 1) Using for loop
list1=[]
for i in L:
    # print(i+2, end=" ,")
    list1.append(i+2)

In [27]:
list1

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [28]:
# 2) Using function
list(map(lambda x:x+2,L))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [29]:
L-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [30]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [31]:
L*2  # multiplyer should be int for rep

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [34]:
L*1.5

TypeError: can't multiply sequence by non-int of type 'float'

In [32]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
a*1.5

array([ 1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ])

In [ ]:
# List store elements of different data type (Mixed datatype)
# Array store elements of same data type (homogeneous)

In [36]:
L2=[1,2,3,"4",5,6]
# 0 1 2  3  4 5

In [37]:
L2

[1, 2, 3, '4', 5, 6]

In [40]:
type(L2[3])

str

In [41]:
type(L2[0])

int

In [43]:
a2=np.array([1,2,3,"4",5,6])

In [45]:
print(a2)

['1' '2' '3' '4' '5' '6']


In [46]:
type(a2[3])

numpy.str_

In [47]:
type(a2[0])

numpy.str_

In [49]:
np.array([1,2,3,4,5,6],dtype=str)

array(['1', '2', '3', '4', '5', '6'], dtype='<U1')

In [50]:
np.array([1,2,3,4,5,6],dtype=int)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Index / Mutability

In [51]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#       0   1   2  3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index

In [ ]:
#6

In [52]:
a[5]

6

In [53]:
a[-5]

6

In [ ]:
#Reverse

In [55]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# variable  [start :       end :              step]
#           0         len(variable)          1     ==> By default
#   ================== Left to Right =====================>

In [ ]:
# 6,7,8

In [56]:
a[5:8]

array([6, 7, 8])

In [62]:
a[-5:-2]

array([6, 7, 8])

In [ ]:
# 8,7,6  


In [64]:
a[7:4:-1]

array([8, 7, 6])

In [ ]:
a[-5:-2]

In [ ]:
#       0   1   2  3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index