In [2]:
import numpy as np  #import numpy

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

In [14]:
L=[0, 1,2,3,"4",5]

In [8]:
np.array(L,dtype=int)

array([1, 2, 3, 4, 5])

In [9]:
np.array(L,dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [11]:
np.array(L,dtype=float)

array([1., 2., 3., 4., 5.])

In [15]:
np.array(L,dtype=bool)

array([False,  True,  True,  True,  True,  True])

In [16]:
np.array(L,dtype=complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
# Indexing/Slicing Homework

In [17]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
#       0   1   2   3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]  ==> Left to right
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a[3]

4

In [20]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a[:3]

array([1, 2, 3])

In [ ]:
# variable  [start :       end :              step]
#           0         len(variable)          1      Default value

In [23]:
a[0] #first element at index position 0 

1

In [24]:
a[1] #second element (index position 1)

2

In [25]:
a[-1] #last element

10

In [26]:
a[2:6] #slicing from index position 2 (incl.) till position 6 (excl.) 

array([3, 4, 5, 6])

In [27]:
#       0   1   2   3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]  ==> Left to right
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index

In [28]:
a[:] #all elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
a[:5] #all elements until index position 5 (excl.)

array([1, 2, 3, 4, 5])

In [30]:
a[6:] #all elements from index position 6 (incl.) till the last element (incl.)

array([ 7,  8,  9, 10])

In [31]:
a[::2] #every second element, starting from first element

array([1, 3, 5, 7, 9])

In [32]:
a[::3] #every third element, starting from first element

array([ 1,  4,  7, 10])

In [33]:
a[2::3] #every third element, starting from third element (index position 2)

array([3, 6, 9])

### Mutability

In [ ]:
# Array is mutable

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
a[5]

6

In [36]:
a[5] = "66666"

In [37]:
a

array([    1,     2,     3,     4,     5, 66666,     7,     8,     9,
          10])

In [40]:
a[-1] =111

In [41]:
a

array([    1,     2,     3,     4,     5, 66666,     7,     8,     9,
         111])

In [ ]:
# Array is iterable

In [42]:
type(a)

numpy.ndarray

In [43]:
for i in a:
    print(i+1)

2
3
4
5
6
66667
8
9
10
112


In [ ]:
# Attributes

In [44]:
a

array([    1,     2,     3,     4,     5, 66666,     7,     8,     9,
         111])

In [46]:
a.shape # tuple represent the dimension of array (rows,columns)

(10,)

In [47]:
a.ndim # Dimension

1

In [48]:
a.size # Number of elemnts ==> similar to len function

10

In [49]:
len(a)

10

In [50]:
a.dtype # datatype of element stired in array  (int, str, float, complex, bool, object)

dtype('int32')

In [51]:
a

array([    1,     2,     3,     4,     5, 66666,     7,     8,     9,
         111])

In [ ]:
# Change datatype of arrays element

In [53]:
a.astype(str)

array(['1', '2', '3', '4', '5', '66666', '7', '8', '9', '111'],
      dtype='<U11')

In [54]:
a.astype(bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [55]:
a.astype(float)

array([1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00,
       6.6666e+04, 7.0000e+00, 8.0000e+00, 9.0000e+00, 1.1100e+02])

In [ ]:
#1D array
a=np.array([1,2,3,4,5])
b = np.array([[1,2,3,4,5,6,7,8,9] , [1,2,3,4,5,6,7,8,9]])
c=np.array([[1,2,3,4],[4,5,6,4],[7,8,9,4]])

In [57]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [63]:
b=np.array([[1,2,3,4,5], [1,2,3,4,5],[1,2,3,4,5]])

In [65]:
b.ndim

2

In [64]:
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [66]:
b.shape

(3, 5)

In [67]:
a=np.array([1,2,3,4,5])

In [68]:
a.shape

(5,)

In [ ]:
1
2
3
4
