In [7]:
import numpy as np 

In [ ]:
# arange: Returns an array with evenly spaced elements as per the step size(by default 1)
# np.arange(start,stop,stepsize (step),dtype)
#              0           +1            Default  # fractional step count is allowed 

# Fractional stepsize not allowed in range

In [ ]:
np.arange(dtype=int,step=2, stop=20, start=10)

In [1]:
range(10)

range(0, 10)

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
tuple(range(10))

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [4]:
set(range(10))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [5]:
list(range(5,20,2))

[5, 7, 9, 11, 13, 15, 17, 19]

In [6]:
list(range(5,20,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
# arange(start,      end,    stepsize,   dtype)
#        optional            optional   optional
#         0                   +1

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
np.arange(5,20,0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [11]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [15]:
np.arange(2,10,2,dtype=float)

array([2., 4., 6., 8.])

In [16]:
np.arange(2,10,2,float)

array([2., 4., 6., 8.])

In [18]:
np.arange(dtype=int,step=2, stop=20, start=10)

array([10, 12, 14, 16, 18])

In [ ]:
#linspace() :- returns evenly spaced numbers over a specified interval.
#linspace(start,  end,  num,    endpoint=True,    retstep=False)
#                      (part)   include/exclud    Gives stepsize
#                     optional    optional        optional
#                       50          True            False

In [30]:
np.linspace(5,15,10,endpoint=True)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [31]:
np.linspace(5,15,10,endpoint=False)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [26]:
np.linspace(1, 10,5,retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [28]:
np.linspace(1, 10,10,endpoint=False,retstep=True)

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [29]:
np.linspace(1, 10,10,endpoint=True,retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [25]:
6.68421053-6.21052632 

0.47368421000000005

In [20]:
a=np.linspace(1, 50)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [21]:
a=np.linspace(1, 10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
#linspace(start,end,num(part))
np.linspace(1, 10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
a=np.linspace(1, 20,10)

In [34]:
a

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [35]:
len(a)

10

In [36]:
np.linspace(1, 20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [37]:
np.linspace(1, 20,10,endpoint=False)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [38]:
np.linspace(1, 20,10,endpoint=False,retstep=True)

(array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1]), 1.9)

In [39]:
print(np.linspace(1, 20,10,endpoint=True,retstep=True))

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]), 2.111111111111111)


In [40]:
np.linspace(1, 20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])