In [1]:
import numpy as np  #import numpy

In [2]:
# Creating 1D array: Excel (perticular column only)

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# Creating  2D array: Excel sheet (Row and columns)

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(arr2d)

numpy.ndarray

In [5]:
# Creating  3D array: Image

arr3d = np.array([[[1, 2, 3], [4, 5, 6]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [6]:
arr.shape

(5,)

In [7]:
arr2d.shape  #(row, column)

(2, 3)

In [8]:
arr3d.shape  #(Frame, row, column)

(1, 2, 3)

In [9]:
np.array([
    [
        [1, 2, 3],
           [4, 5, 6],
           [4, 5, 6]
    ],
          
          [
              [1, 2, 3],
           [4, 5, 6],
           [4, 5, 6]
          ]
]).shape

(2, 3, 3)

In [10]:
# Reshape : Change shape of array
# M1
# Array.reshape(shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

# M2
# np.reshape(data,shape,order(Fill_by))
# shape= (row,col)
# order (Fill_by) "C" ===> Fill_by Row
#         "F" ===> Fill_by column


In [11]:
a=np.arange(1,13)

In [12]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
a.ndim

1

In [14]:
a.shape

(12,)

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
len(a)

12

In [17]:
# Array.reshape(shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [23]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
a.reshape((4,3),order="C") # Need to define parameter name "order"

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
a.reshape((4,3),order="F")

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [53]:
np.reshape(a,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
np.reshape(a,(4,3),"C")

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
np.reshape(a,(4,3),"F")

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [56]:
# M2
# np.reshape(data,shape,order(Fill_by))
# shape= (row,col)
# order (Fill_by) "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [57]:
# How define shape

In [58]:
a.size

12

In [59]:
np.reshape(a,(4,2),"F")  # If values is less than new shape we got error

ValueError: cannot reshape array of size 12 into shape (4,2)

In [60]:
np.reshape(a,(4,4),"F")  # If values is less than new shape we got error

ValueError: cannot reshape array of size 12 into shape (4,4)

In [61]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

In [62]:
c=np.arange(27)

In [63]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [64]:
c.size

27

In [65]:
np.reshape(c,(9,3),"F")

array([[ 0,  9, 18],
       [ 1, 10, 19],
       [ 2, 11, 20],
       [ 3, 12, 21],
       [ 4, 13, 22],
       [ 5, 14, 23],
       [ 6, 15, 24],
       [ 7, 16, 25],
       [ 8, 17, 26]])

In [66]:
np.reshape(c,(3,3,3),"F")

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [67]:
b=list(range(1,13))

In [68]:
b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [76]:
b.reshape((4,3))

AttributeError: 'list' object has no attribute 'reshape'

In [74]:
b2=np.arange(1,13)

In [75]:
b2.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
np.reshape(b,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])