In [3]:
import numpy as np  #import numpy

In [4]:
# Reshape:

# M1
# np.reshape(data,shape,order(Fill_by))
# shape= (row,col)
# order (Fill_by) "C" ===> Fill_by Row
#         "F" ===> Fill_by column

# M2
# Array.reshape(shape,Fill_by)  # need to define parameter name order
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [30]:
a=np.arange(1,11)

In [31]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# M1

In [13]:
a.reshape((2,5),order="F")

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [15]:
a.reshape((2,5),"F")

TypeError: 'tuple' object cannot be interpreted as an integer

In [16]:
a.reshape((2,5),order="F")

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [17]:
a.reshape(2,5,order="F")

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [ ]:
# M2

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
c=np.reshape(a,(2,5),"C")

In [23]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.reshape(a,(2,5),order="F")

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [ ]:
np.reshape(a,(2,6),"C")

In [25]:
#Examples

In [26]:
a = np.arange(18).reshape(3,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [ ]:
a = np.arange(15).reshape(3,5) #rowwise
print(a)

In [ ]:
a = np.arange(15).reshape((3,5),order="F") #columnwise
print(a)

In [ ]:
a = np.arange(15).reshape(2,7)
print(a)

In [ ]:
a = np.arange(16)
print(a)

In [ ]:
a = np.arange(16).reshape(2,8)
print(a)

In [ ]:
a = np.arange(16).reshape(4,4)
print(a)

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) # Matrix of 4x4
print(a)

In [ ]:
a.ndim

In [ ]:
a.size

In [ ]:
a = a.reshape(2,8) # Reshape 2x8
print(a)

In [ ]:
a = a.reshape(8,2) # Reshape 2x8
print(a)

In [ ]:
a = a.reshape(4,4) 
print(a)

In [ ]:
a = a.reshape(16,1) 
print(a)

In [ ]:
a = a.reshape(1,16) 
print(a)

In [ ]:
#resize()
# It changes the original array directly and does not return a new array

In [34]:
# M1) array.resize(new_shape) 
      # Input data (array) must be array. 
      # Change in itself does not create new array
# M2) np.resize(input1_dat,new_shape) 
      # input data may be array, list, tuple
      # It create new array

# If required values is less or grater then we can handle using reference check =False (refcheck=False). By deafault refcheck=True

In [44]:
a2=np.arange(1,13)

In [45]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
a2.resize(4,3)  #1,12  4,3  3,4  12,1

In [47]:
k2=a2.resize(4,3)

In [48]:
k2

In [49]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
a2.resize(3,4)

In [51]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
a2.resize(3,5,refcheck=False)

In [54]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  0,  0,  0]])

In [56]:
b2=list(range(1,13))

In [57]:
b2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [58]:
np.resize(b2,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
b2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [60]:
b3=np.arange(1,13)

In [61]:
np.resize(b3,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
b3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Transpose

In [ ]:
# M1) arr.T
# M2) arr.transpose()

In [63]:
arr=np.arange(1,13)

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
arr.resize(4,3)

In [66]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
arr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [69]:
arr.T.T

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
arr.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [71]:
arr.T.T.T.T

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])