## Create array with initial values

In [50]:
# # Methods
# np.array()
# np.arange()
# np.linspace()

# # With initial values
# np.eye():Creates an identity matrix
# np.zeros:Creates an array filled with zeros
# np.ones():Creates an array filled with ones
# np.full():Creates an array filled with a specified value
# np.empty() : Create with random values

In [51]:
import numpy as np

In [52]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [53]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [55]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [58]:
np.full((4,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [59]:
np.full((4,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [60]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.52166653e-321, 1.78019082e-306,
        1.37959740e-306]])

### Indexing and slicing NumPy arrays:

In [1]:
import numpy as np

In [2]:
arr=np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

1

In [5]:
arr[1:4]

array([2, 3, 4])

In [6]:
arr[1:4:2]

array([2, 4])

In [7]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Indexing and Slicing multi-dimensional arrays

In [ ]:
# Multiple dimension array: 2D
# M1) variable_name[row,column]
# M2) variable_name[row][column]

In [ ]:
# Multiple dimension array:3D
# M1) variable_name[Frame,row,column]
# M2) variable_name[Frame][row][column]

In [9]:
import numpy as np

In [10]:
arr=np.arange(2,42,2)

In [11]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [12]:
arr.size

20

In [13]:
b=arr.reshape(4,5)

In [14]:
b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [15]:
print(b)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [ ]:
#             -5 -4  -3 -2 -1
# Rows Columns 0  1  2  3  4  
#    0      [[ 2  4  6  8 10]
#    1       [12 14 16 18 20]
#    2       [22 24 26 28 30]
#    3       [32 34 36 38 40]]

In [ ]:
# M1) variable_name[row,column]

In [32]:
b[: ,-1]

array([10, 20, 30, 40])

In [33]:
b[: : -1,-1]

array([40, 30, 20, 10])

In [ ]:
# Homework

# # Retrive following value from array b
# 1) 14
# 2) 28
# 3) 6
# 4) 34

# 5) 24,26,28

# 6) 14,16
#    24,26

# 7)[22, 24, 26, 28, 30]
#   [32, 34, 36, 38, 40]
    
# 8) 4
#    14
#     24
#     34

In [39]:
#36
# M1)
b[3,2]


36

In [40]:
#36
# M2)
b[3][2]

36

In [41]:
# 6   8
# 16  18
b[0,2:4]

array([6, 8])

In [42]:
# 6  8
b[0:2,2:4]

b[0:2][2:4]

array([], shape=(0, 5), dtype=int32)

In [43]:
b[-1]

array([32, 34, 36, 38, 40])

In [44]:
b[:,-1]

array([10, 20, 30, 40])

In [45]:
b[: : -1,-1]

array([40, 30, 20, 10])

In [46]:
c=[10, 20, 30, 40]

In [47]:
c[: : -1]

[40, 30, 20, 10]

In [48]:
c[0:4 : -1]

[]

In [49]:
c[4: : -1]

[40, 30, 20, 10]

In [19]:
b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [20]:
b[0] #first row (index position 0)

array([ 2,  4,  6,  8, 10])

In [21]:
b[1] #second row (index position 1)

array([12, 14, 16, 18, 20])

In [23]:
b[2] #third row (index position 2)

array([22, 24, 26, 28, 30])

In [22]:
b[-1] #last row (index position -1)

array([32, 34, 36, 38, 40])

In [24]:
b[1][1] #second row, second column

14

In [25]:
b[1,1] #more convenient in one square bracket

14

In [26]:
b[2,-1] #third row, last column

30

In [27]:
b[:,0] #all rows, first column

array([ 2, 12, 22, 32])

In [28]:
b[: :-1,0]

array([32, 22, 12,  2])

In [29]:
b[:,1] #all rows, second column

array([ 4, 14, 24, 34])

In [ ]:
#             -5 -4  -3 -2 -1
# Rows Columns 0  1  2  3  4  
#    0      [[ 2  4  6  8 10]
#    1       [12 14 16 18 20]
#    2       [22 24 26 28 30]
#    3       [32 34 36 38 40]]

In [30]:
b[:,-1] #all rows, last column

array([10, 20, 30, 40])

In [31]:
b[:2,1:3] #first two rows, column two and three

array([[ 4,  6],
       [14, 16]])