In [ ]:
# Convert multi-dimensional arrays into one-dimensional arrays
# M1) ravel :NumPy function (np.ravel() / arr.ravel()) : returns a view of the original array. Changes to the new array may affect the original array and vice versa.
# M2) flatten :Array method (arr.flatten()) : returns a copy of the original array. Changes to the new array do not affect the original array.
# M3) reshape / resize

In [2]:
import numpy as np

In [5]:
a=np.arange(1,21).reshape(5,4)

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [7]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
# np.flatten(a) # does not works

In [11]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
ravel_out=a.ravel()

In [13]:
flatten_out=a.flatten()

In [14]:
ravel_out

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
flatten_out

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
flatten_out[2]=333

In [18]:
flatten_out

array([  1,   2, 333,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [20]:
a[1,1]

6

In [21]:
a[1,1]=666

In [22]:
a

array([[  1,   2,   3,   4],
       [  5, 666,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [23]:
flatten_out

array([  1,   2, 333,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [24]:
ravel_out

array([  1,   2,   3,   4,   5, 666,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [28]:
a

array([[  1,   2,   3,   4],
       [  5, 666,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [29]:
ravel_out[4]=555

In [30]:
ravel_out

array([  1,   2,   3,   4, 555, 666,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [33]:
ravel_out.shape

(20,)

In [31]:
a

array([[  1,   2,   3,   4],
       [555, 666,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [ ]:
# ravel and flatten method used to convert multi dimensional array to 1D array
# If you change any element either its output or original array it will reflect each other when we used ravel
# If you change any element either its output or original array it does not reflect each other when we used flatten. Changes reflected itself only

In [32]:
a

array([[  1,   2,   3,   4],
       [555, 666,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [34]:
a.reshape((20,))

array([  1,   2,   3,   4, 555, 666,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [35]:
l=list(range(2,22,2))

In [ ]:
# Find out summation of elements stored in above list

In [36]:
l

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
for x in l:
    l.append(l+2)

In [37]:
list_sum=0
for x in l:
    list_sum=list_sum+x
    

In [38]:
list_sum

110

In [40]:
a=np.arange(2,22,2)

In [41]:
a.sum()

110