### Mathematical functions

In [1]:
import numpy as np

In [2]:
b=np.arange(2,41,2).reshape((5,4),order="F")

In [3]:
print(b)

[[ 2 12 22 32]
 [ 4 14 24 34]
 [ 6 16 26 36]
 [ 8 18 28 38]
 [10 20 30 40]]


In [4]:
b.sum() #sum over all elements in matrix

420

In [5]:
b.sum(axis = 0) #sum of each column

array([ 30,  80, 130, 180])

In [6]:
22+24+26+28+30

130

In [7]:
b.sum(axis = 1) #sum of each row

array([ 68,  76,  84,  92, 100])

In [8]:
 4 +14+ 24+ 34

76

In [ ]:
b

In [9]:
b.sum()

420

In [11]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [10]:
b.cumsum() #cumulative sum of all elements

array([  2,  14,  36,  68,  72,  86, 110, 144, 150, 166, 192, 228, 236,
       254, 282, 320, 330, 350, 380, 420])

In [12]:
b.cumsum(axis = 0) #cumulative sum for each column

array([[  2,  12,  22,  32],
       [  6,  26,  46,  66],
       [ 12,  42,  72, 102],
       [ 20,  60, 100, 140],
       [ 30,  80, 130, 180]])

In [13]:
b.cumsum(axis = 1) #cumulative sum for each row

array([[  2,  14,  36,  68],
       [  4,  18,  42,  76],
       [  6,  22,  48,  84],
       [  8,  26,  54,  92],
       [ 10,  30,  60, 100]])

In [14]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [15]:
b.max() #maximum 

40

In [16]:
b.max(axis=0) #maximum 

array([10, 20, 30, 40])

In [17]:
b.max(axis=1) #maximum 

array([32, 34, 36, 38, 40])

In [18]:
b.min() #minimum 

2

In [19]:
b.mean() #mean 

21.0

In [20]:
L=list(range(2,41,2))

In [21]:
L

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]

In [22]:
# mean = summation of all elements / total number of elements

In [24]:
L.mean()

AttributeError: 'list' object has no attribute 'mean'

In [28]:
a=sum(L)/len(L)
a

21.0

In [31]:
sum=0
for num in L:
    sum=sum+num
    a=sum/len(L)

In [32]:
a

21.0

In [25]:
np.mean(L)

21.0

In [33]:
# b.mean() ==> Works if b is array
# If b is not array then use ==> np.mean(b)

In [34]:
np.median(b) #median

21.0

In [36]:
b.std() #standard deviation  ==> np.std(b)

11.532562594670797

In [38]:
11.532562594670797*11.532562594670797

133.00000000000003

In [37]:
b.var() #variance

133.0

In [ ]:
# square of std is equal to variance

In [39]:
np.percentile(b, 10) #10th percentile

5.800000000000001

In [40]:
np.percentile(b, 50) #median

21.0

In [41]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [42]:
np.sqrt(b) #square root of all elements

array([[1.41421356, 3.46410162, 4.69041576, 5.65685425],
       [2.        , 3.74165739, 4.89897949, 5.83095189],
       [2.44948974, 4.        , 5.09901951, 6.        ],
       [2.82842712, 4.24264069, 5.29150262, 6.164414  ],
       [3.16227766, 4.47213595, 5.47722558, 6.32455532]])

In [43]:
np.exp(b) #exponentiation with e

array([[7.38905610e+00, 1.62754791e+05, 3.58491285e+09, 7.89629602e+13],
       [5.45981500e+01, 1.20260428e+06, 2.64891221e+10, 5.83461743e+14],
       [4.03428793e+02, 8.88611052e+06, 1.95729609e+11, 4.31123155e+15],
       [2.98095799e+03, 6.56599691e+07, 1.44625706e+12, 3.18559318e+16],
       [2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17]])

In [44]:
np.log(b) #natural logarithm

array([[0.69314718, 2.48490665, 3.09104245, 3.4657359 ],
       [1.38629436, 2.63905733, 3.17805383, 3.52636052],
       [1.79175947, 2.77258872, 3.25809654, 3.58351894],
       [2.07944154, 2.89037176, 3.33220451, 3.63758616],
       [2.30258509, 2.99573227, 3.40119738, 3.68887945]])

In [45]:
c = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
c

array([-1.7, -1.5, -0.2,  0.2,  1.5,  1.7,  2. ])

In [46]:
np.abs(c) #absolute values of all elements

array([1.7, 1.5, 0.2, 0.2, 1.5, 1.7, 2. ])

In [ ]:
 # |-2| = 2 #absolute

In [47]:
d=np.array([1.7, 3.1, 0.2, 4.2, 1.5, 2.7, 5.2 ])

In [48]:
d

array([1.7, 3.1, 0.2, 4.2, 1.5, 2.7, 5.2])

In [49]:
np.ceil(d) #element-wise rounding up

array([2., 4., 1., 5., 2., 3., 6.])

In [50]:
np.floor(d) #element-wise rounding down

array([1., 3., 0., 4., 1., 2., 5.])