In [1]:
import numpy as np

In [ ]:
45.465376

In [2]:
round(45.465376,1)

45.5

In [3]:
round(45.465376,2)

45.47

In [4]:
round(45.465376,3)

45.465

In [5]:
a=np.array([-3.23, -0.76, 1.44, 2.65])

In [7]:
np.abs(a)

array([3.23, 0.76, 1.44, 2.65])

In [8]:
a

array([-3.23, -0.76,  1.44,  2.65])

In [9]:
np.around(a, decimals = 1) #evenly round all elements to the given number of decimals.

array([-3.2, -0.8,  1.4,  2.6])

In [10]:
np.around(a, decimals = 0) #evenly round all elements to the given number of decimals.

array([-3., -1.,  1.,  3.])

### Matrix

In [ ]:
# Element-wise operations:
# Addition: np.add()
# Subtraction: np.subtract()
# Division: np.divide()
# Multiplication: np.multiply()

In [11]:
# Define two matrices to multiply
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 7]])

In [12]:
print(matrix1)

[[1 2]
 [3 4]]


In [13]:
print(matrix2)

[[5 6]
 [7 7]]


In [ ]:
# Addition:

In [15]:
matrix1 + matrix2

array([[ 6,  8],
       [10, 11]])

In [14]:
np.add(matrix1,matrix2)

array([[ 6,  8],
       [10, 11]])

In [ ]:
# Subtraction:

In [16]:
matrix1 - matrix2

array([[-4, -4],
       [-4, -3]])

In [19]:
matrix1

array([[1, 2],
       [3, 4]])

In [20]:
matrix2

array([[5, 6],
       [7, 7]])

In [17]:
np.subtract(matrix1,matrix2)

array([[-4, -4],
       [-4, -3]])

In [18]:
np.subtract(matrix2,matrix1)

array([[4, 4],
       [4, 3]])

In [21]:
# Division:

In [22]:
matrix1 / matrix2

array([[0.2       , 0.33333333],
       [0.42857143, 0.57142857]])

In [23]:
np.divide(matrix1,matrix2)

array([[0.2       , 0.33333333],
       [0.42857143, 0.57142857]])

In [24]:
matrix1

array([[1, 2],
       [3, 4]])

In [25]:
matrix2

array([[5, 6],
       [7, 7]])

In [26]:
# Multiplication:

In [27]:
matrix1 * matrix2

array([[ 5, 12],
       [21, 28]])

In [29]:
np.multiply(matrix1,matrix2)

array([[ 5, 12],
       [21, 28]])

### Linear Algebra

In [ ]:
# np.dot(): Computes the dot product of two arrays. 
# np.linalg.inv(): Computes the inverse of a matrix.
# np.linalg.det(): Computes the determinant of a matrix.
# np.linalg.eig(): Computes the eigenvalues and right eigenvectors of a square array.

In [32]:
matrix1

array([[1, 2],
       [3, 4]])

In [33]:
matrix2

array([[5, 6],
       [7, 7]])

In [30]:
# Method 1: Using np.dot()
result1 = np.dot(matrix1, matrix2)
print(result1)

[[19 20]
 [43 46]]


In [31]:
# Method 2: Using @ operator
result2 = matrix1 @ matrix2
print(result2)

[[19 20]
 [43 46]]


In [34]:
# Compute the determinant
matrix = np.array([[1, 2], [3, 4]])

In [35]:
matrix

array([[1, 2],
       [3, 4]])

In [36]:
det = np.linalg.det(matrix)
print(round(det,2))

-2.0


In [37]:
# calculate the inverse
matrix_inv = np.linalg.inv(matrix)

print(matrix_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [38]:
#cross check     
matrix @ matrix_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [39]:
np.around(matrix @ matrix_inv)

array([[1., 0.],
       [0., 1.]])

In [40]:
np.linalg.eig(matrix)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [43]:
b=matrix.reshape((4,))

In [ ]:
1,2,3,4

In [44]:
b

array([1, 2, 3, 4])

In [45]:
b.max()

4

In [46]:
c=[1, 2, 3, 4]

In [47]:
c.max()

AttributeError: 'list' object has no attribute 'max'

In [48]:
np.max(c)

4

In [51]:
np.arange(1,28).size

27

In [52]:
np.arange(1,28).reshape(3,3,3)
                #    Frame  row column

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [53]:
5*3*4

60

In [ ]:
4,3,5

In [55]:
np.arange(1,61).reshape(4,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45]],

       [[46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [ ]:
# linespace()

In [ ]:
#Exercise

In [ ]:
#Create array values and practice following examples
arr=np.arange(10).reshape(5,2)

In [ ]:
# Finding the mean of a NumPy array:

mean_val = np.mean(arr)
mean_val

In [ ]:
# Finding the median of a NumPy array:

median_val = np.median(arr)
median_val

In [ ]:
# Finding the standard deviation of a NumPy array:

std_val = np.std(arr)
std_val

In [ ]:
var_val = np.var(arr)
var_val

In [ ]:
# Performing element-wise operations on NumPy arrays:

arr_squared = arr ** 2
arr_squared

In [ ]:
# create an array of data
data = np.arange(100)

# calculate the mean
mean = np.mean(data)
print("Mean:", mean)

# calculate the median
median = np.median(data)
print("Median:", median)

# calculate the variance
variance = np.var(data)
print("Variance:", variance)

# calculate the standard deviation
std_dev = np.std(data)
print("Standard deviation:", std_dev)

# calculate the minimum and maximum values
minimum = np.min(data)
maximum = np.max(data)
print("Minimum:", minimum)
print("Maximum:", maximum)